---
    - name: Download Node Exporter archive
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.2.0/node_exporter-1.2.0.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter.tar.gz"

    - name: Extract Node Exporter archive
      unarchive:
        src: "/tmp/node_exporter.tar.gz"
        dest: "/opt"
        remote_src: true
        extra_opts: [--strip-components=1]
        creates: "/opt/node_exporter"

    - name: Create Node Exporter user
      user:
        name: node_exporter
        system: yes
        shell: /bin/false

    - name: Set ownership and permissions
      file:
        path: "/opt/node_exporter"
        owner: node_exporter
        group: node_exporter
        mode: "0755"

    - name: Configure Node Exporter systemd service
      systemd:
        name: node_exporter
        daemon_reload: yes
        enabled: yes
        state: daemon-reload
        #user: node_exporter
        executable: /opt/node_exporter/node_exporter

    - name: Open port for Node Exporter
      ufw:
        rule: allow
        port: 9100
        state: enabled
