---
   - name: Install pip3 for Ubuntu/Debian
     become: true
     apt:
       name: python3-pip
       state: present
   - name: Install Python packages from requirements.txt
     pip:
       requirements: /home/ubuntu/monitoring/roles/install-dependencies/tasks/requirements.txt
