---
- name: Install Python dependencies
  become: true
  tasks:
    - name: Install Python packages from requirements.txt
      pip:
        requirements: roles/install-dependencies/tasks/requirements.txt
